poireau/common/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from . import views


urlpatterns = patterns(
    '',
    # Apps
    url(r'^songs/', include('poireau.songs.urls', namespace="songs")),
    url(r'^dropbox/', include('poireau.dropbox_sync', namespace="dropbox_sync")),
    url(r'^admin/', include(admin.site.urls)),

    # Base views
    url(r'^$', views.HomeView.as_view(), name="home"),
    url(r'^auth/login', views.LoginView.as_view(), name="login"),
    url(r'^auth/logout', views.LogoutView.as_view(), name="logout"),

)

poireau/songs/urls.py
from django.conf.urls import patterns, url

from .views import song, discover


urlpatterns = patterns(
    '',
    url(r'^songs$', song.SongListView.as_view(), name='song_list'),

    url(r'^songs/discover/dropbox$', discover.DropboxSyncView.as_view(), name='songs_dropbox_sync'),
    url(r'^songs/compare$', discover.SongCompareView.as_view(), name='songs_compare'),

    url(r'^song/(?P<pk>\d+)$', song.SongDetailView.as_view(), name='song_detail'),
    url(r'^song/random$', song.SongRandomView.as_view(), name='song_random'),
)

poireau/songs/models/part.py
# -*- coding: utf-8 -*-

from django.db import models
from django.utils.translation import ugettext_lazy as _


class Part(models.Model):

    NOTES = (
        ("a", _("A")),
        ("b", _("B")),
        ("c", _("C")),
        ("d", _("D")),
        ("e", _("E")),
        ("f", _("F")),
        ("g", _("G")),
    )
    ACCIDENTALS = (
        ("flat", _("♭")),
        ("natural", ""),
        ("sharp", _("♯")),
    )
    NOTES_ORDER = "cdefgab"

    name = models.CharField(max_length=64)
    song = models.ForeignKey(
        "songs.Song", related_name='parts',
        verbose_name=_("Song")
    )
    section = models.ForeignKey(
        "singers.Section", related_name='parts',
        verbose_name=_("Section"), blank=True, null=True)
    first_note_midi = models.IntegerField(
        verbose_name=_("First note"), blank=True, null=True
    )
    first_note_accidental = models.CharField(
        max_length=1, choices=ACCIDENTALS, default="natural",
        verbose_name=_("First note accidental"), blank=True
    )

    @property
    def first_note(self):
        return Note(self.first_note_midi, self.first_note_accidental)

    @first_note.setter
    def first_note(self, note):
        self.first_note_midi = note.midi_value
        self.first_note_accidental = note.accidental

    def __str__(self):
        return "{} - {}".format(self.song.name, self.name)

    class Meta(object):
        app_label = "songs"
        verbose_name = _("Part")
        verbose_name_plural = _("Parts")
        unique_together = [("name", "song")]


class Note(object):
    def __init__(self, midi_value, accidental="natural"):
        """
        Midi values : 1 per half tone, C4 == 60
        1 octave == 12 half tones == 12 values. 0 would be "C-1"
        """
        self.midi_value = midi_value
        self.note = Part.NOTES_ORDER[midi_value % 12]
        self.octave = midi_value // 12 - 1
        self.accidental = accidental

    def __str__(self):
        return "{note}{accidental}{octave}".format(
            note=dict(Part.NOTES)[self.note],
            accidental=dict(Part.ACCIDENTALS)[self.accidental],
            octave=_(" (oct. {})").format(self.octave)
        )

poireau/songs/forms.py
import os

from django import forms
from django.utils.translation import ugettext_lazy as _


class FolderChoice(forms.Form):
    folder = forms.ChoiceField(
        choices=tuple(), label=_("Folder"), help_text=_("The Dropbox folder that contains the songs."),
        required=False
    )

    def __init__(self, folders, *args, **kwargs):
        super(FolderChoice, self).__init__(*args, **kwargs)

        self.fields["folder"].choices = sorted([
            (dir_path, os.path.basename(dir_path))
            for dir_path in folders
        ])


class DiscoverForm(forms.Form):
    field_pattern = "song_{}"

    def __init__(self, songs, *args, **kwargs):
        super().__init__(*args, **kwargs)
        choices = [("", _("Nothing : Delete this song"))] + [
            (song.tmp_id, song.title)
            for song in songs["appeared"]
        ]
        for song in songs["disappeared"]:
            self.fields["song_{}".format(song.id)] = forms.ChoiceField(
                choices=choices, label=_("Replace {} by :").format(song), required=False
            )

poireau/songs/views/discover.py
import pickle

import dropbox

from django.views.generic import FormView
from django.core.urlresolvers import reverse_lazy as reverse
from django.apps import apps
from django.conf import settings
from django.db import transaction

from poireau.dropbox_sync.models import FolderSync
from poireau.dropbox_sync.views import DropboxTokenMixin
from poireau.common.utils import FilesManager

from ..forms import FolderChoice, DiscoverForm
from ..utils.xml_song import FoundSong
from .song import SongMixin
from ..models import Song, Part


class DropboxSyncView(DropboxTokenMixin, SongMixin, FormView):
    template_name = "base/form.html"
    form_class = FolderChoice
    mode = None

    def get_form_kwargs(self):
        kwargs = super(DropboxSyncView, self).get_form_kwargs()
        self.client = dropbox.Dropbox(self.dropbox_access_token)
        entries = self.client.files_list_folder('', recursive=False).entries
        kwargs["folders"] = [entry.name for entry in entries if isinstance(entry, dropbox.files.FolderMetadata)]

        return kwargs

    def form_valid(self, form):
        changes = FolderSync.sync_folder(
            dropbox_client=self.client,
            local_base_dir=settings.SONGS_FOLDER,
            dropbox_path="/" + form.cleaned_data["folder"]
        )
        self.request.session["LATEST_CHANGES"] = changes
        self.success_url = reverse("songs:songs_compare")

        return super(DropboxSyncView, self).form_valid(form)


class SongCompareView(SongMixin, FormView):
    template_name = "songs/compare.html"
    form_class = DiscoverForm

    def to_session(self, songs):
        return pickle.dumps(songs)

    def from_session(self):
        return pickle.loads(self.request.session["DISCOVERED_SONGS"])

    @property
    def songs(self):
        files_manager = FilesManager()

        if hasattr(self, "_songs"):
            return self._songs
        elif "DISCOVERED_SONGS" in self.request.session:
            self._songs = self.from_session(files_manager)
        else:
            folder = settings.SONGS_FOLDER

            found_songs = [
                FoundSong(dir_path, file_name, files_manager)
                for dir_path, __, file_names in files_manager.walk(folder)
                for file_name in file_names
                if file_name.endswith(".xml")
            ]

            Song = apps.get_model("songs.Song")
            reference_songs = [song.xml_song for song in Song.objects.all()]
            appeared, disappeared, updated = FoundSong.compare_sets(reference_songs, found_songs)
            songs = {
                "appeared": appeared,
                "disappeared": disappeared,
                "updated": updated,
            }
            self._songs = songs
            self.to_session(songs)

        return self._songs

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["songs"] = self.songs
        return kwargs

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)
        context_data["songs"] = self.songs
        if "LATEST_CHANGES" in self.request.session:
            context_data["changes"] = self.request.session["LATEST_CHANGES"]

        return context_data

    @transaction.atomic
    def form_valid(self, form):

        songs = self.songs
        disappeared_by_id = {song.id: song for song in songs["disappeared"]}
        appeared_by_id = {song.tmp_id: song for song in songs["appeared"]}

        mapping = {}
        for disappeared_field_name, appeared_tmp_id in form.cleaned_data.items():
            if not appeared_tmp_id:
                continue
            disappeared_id = int(disappeared_field_name[DiscoverForm.field_pattern.index("{}"):])
            mapping[disappeared_by_id[disappeared_id]] = appeared_by_id[appeared_tmp_id]

        songs_to_create = []
        for song in set(songs["appeared"]) - set(mapping.values()):
            songs_to_create.append(song.to_model_song())
        paths = [song.path for song in songs_to_create]

        Song.objects.bulk_create(songs_to_create)

        parts_to_create = []
        for songs_created in Song.objects.filter(path__in=paths):
            # parts_to_create.extend(songs_created.create_model_parts())
            for part in songs_created.create_model_parts():
                part.save()

        Part.objects.bulk_create(parts_to_create)

        songs_to_delete = [
            song.id
            for song in set(songs["disappeared"]) - set(mapping.keys())
        ]
        Song.objects.filter(id__in=songs_to_delete)

        songs["updated"].update(mapping)

        for new_song, old_song in songs["updated"].items():
            new_song.update_from(old_song)

        return super().form_valid(form)

    def get_success_url(self):
        return reverse("songs:song_list")

poireau/songs/views/dropbox.py
import logging

from dropbox.client import DropboxOAuth2Flow

from django.conf import settings
from django import http
from django.core.urlresolvers import reverse
from django.views.generic import View, RedirectView
from django.contrib import messages
from django.utils.translation import ugettext_lazy as _

from poireau.common.views import BaseLoggedViewMixin

LOGGER = logging.getLogger(__name__)

DROPBOX_TOKEN_SESSION_KEY = "dropbox_access_token"


class DropboxMixin(object):
    def get_dropbox_auth_flow(self):
        redirect_uri = self.request.build_absolute_uri(reverse("songs:dropbox_finish"))
        return DropboxOAuth2Flow(settings.DROPBOX_APP_KEY, settings.DROPBOX_APP_SECRET, redirect_uri,
                                 self.request.session, "dropbox-auth-csrf-token")


class DropboxStartView(BaseLoggedViewMixin, DropboxMixin, RedirectView):
    permanent = True

    def get_redirect_url(self):
        authorize_url = self.get_dropbox_auth_flow().start()
        return authorize_url


class DropboxFinishView(BaseLoggedViewMixin, DropboxMixin, View):
    # URL handler for /dropbox-auth-finish
    def get(self, request):
        try:
            access_token, __, __ = self.get_dropbox_auth_flow().finish(self.request.GET)

        except DropboxOAuth2Flow.BadRequestException as exc:
            return http.HttpResponseBadRequest()

        except DropboxOAuth2Flow.BadStateException as exc:
            # Start the auth flow again.
            return http.HttpResponseRedirect(reverse("songs:dropbox_start"))

        except DropboxOAuth2Flow.CsrfException as exc:
            LOGGER.error("CSRF error: {}".format(exc))
            return http.HttpResponseForbidden()

        except DropboxOAuth2Flow.NotApprovedException as exc:
            messages.error(request, _("You have not authorized the application."))
            return http.HttpResponseRedirect(reverse("home"))

        except DropboxOAuth2Flow.ProviderException as exc:
            LOGGER.error("Auth error: {}".format(exc))
            return http.HttpResponseForbidden()

        request.session[DROPBOX_TOKEN_SESSION_KEY] = access_token
        request.user.dropbox_token = access_token
        request.user.save()

        return http.HttpResponseRedirect(reverse("songs:songs_choose_folder_dropbox"))


class DropboxTokenMixin(object):

    class NoToken(Exception):
        pass

    def dispatch(self, request, *args, **kwargs):
        self.dropbox_access_token = ""
        try:
            self.dropbox_access_token = request.session[DROPBOX_TOKEN_SESSION_KEY]
        except KeyError:
            pass

        if not self.dropbox_access_token:
            self.dropbox_access_token = request.session[DROPBOX_TOKEN_SESSION_KEY] = request.user.dropbox_token

        if self.dropbox_access_token:
            return super(DropboxTokenMixin, self).dispatch(request, *args, **kwargs)
        else:
            return http.HttpResponseRedirect(reverse("songs:dropbox_start"))

poireau/songs/views/dropbox_utils.py
import logging

from dropbox.client import DropboxOAuth2Flow

from django.conf import settings
from django import http
from django.core.urlresolvers import reverse
from django.views.generic import View, RedirectView
from django.contrib import messages
from django.utils.translation import ugettext_lazy as _

from poireau.common.views import BaseLoggedViewMixin

LOGGER = logging.getLogger(__name__)

DROPBOX_TOKEN_SESSION_KEY = "dropbox_access_token"


class DropboxMixin(object):
    def get_dropbox_auth_flow(self):
        redirect_uri = self.request.build_absolute_uri(reverse("songs:dropbox_finish"))
        return DropboxOAuth2Flow(settings.DROPBOX_APP_KEY, settings.DROPBOX_APP_SECRET, redirect_uri,
                                 self.request.session, "dropbox-auth-csrf-token")


class DropboxStartView(BaseLoggedViewMixin, DropboxMixin, RedirectView):
    permanent = True

    def get_redirect_url(self):
        authorize_url = self.get_dropbox_auth_flow().start()
        return authorize_url


class DropboxFinishView(BaseLoggedViewMixin, DropboxMixin, View):
    # URL handler for /dropbox-auth-finish
    def get(self, request):
        try:
            access_token, __, __ = self.get_dropbox_auth_flow().finish(self.request.GET)

        except DropboxOAuth2Flow.BadRequestException as exc:
            return http.HttpResponseBadRequest()

        except DropboxOAuth2Flow.BadStateException as exc:
            # Start the auth flow again.
            return http.HttpResponseRedirect(reverse("songs:dropbox_start"))

        except DropboxOAuth2Flow.CsrfException as exc:
            LOGGER.error("CSRF error: {}".format(exc))
            return http.HttpResponseForbidden()

        except DropboxOAuth2Flow.NotApprovedException as exc:
            messages.error(request, _("You have not authorized the application."))
            return http.HttpResponseRedirect(reverse("home"))

        except DropboxOAuth2Flow.ProviderException as exc:
            LOGGER.error("Auth error: {}".format(exc))
            return http.HttpResponseForbidden()

        request.session[DROPBOX_TOKEN_SESSION_KEY] = access_token
        request.user.dropbox_token = access_token
        request.user.save()

        return http.HttpResponseRedirect(reverse("songs:songs_choose_folder_dropbox"))


class DropboxTokenMixin(object):

    class NoToken(Exception):
        pass

    def dispatch(self, request, *args, **kwargs):
        self.dropbox_access_token = ""
        try:
            self.dropbox_access_token = request.session[DROPBOX_TOKEN_SESSION_KEY]
        except KeyError:
            pass

        if not self.dropbox_access_token:
            self.dropbox_access_token = request.session[DROPBOX_TOKEN_SESSION_KEY] = request.user.dropbox_token

        if self.dropbox_access_token:
            return super(DropboxTokenMixin, self).dispatch(request, *args, **kwargs)
        else:
            return http.HttpResponseRedirect(reverse("songs:dropbox_start"))

poireau/songs/views/song.py
from django.views.generic import View, ListView, DetailView
from django import http
from django.core.urlresolvers import reverse_lazy as reverse

from poireau.common.views import BaseLoggedViewMixin
from poireau.songs.models import Song


class SongMixin(BaseLoggedViewMixin):
    model = Song


class SongListView(SongMixin, ListView):
    template_name = "songs/list.html"
    menu_list = ["songs"]

    def get_queryset(self):
        return sorted(
            super(SongListView, self).get_queryset(),
            key=lambda song: song.sort_key
        )


class SongDetailView(SongMixin, DetailView):
    template_name = "songs/detail.html"
    menu_list = ["songs"]


class SongRandomView(SongMixin, View):

    def get(self, request):
        song = Song.objects.order_by("?").first()
        if song:
            return http.HttpResponseRedirect(song.get_absolute_url())
        else:
            return http.HttpResponseRedirect(reverse("songs:song_list"))

poireau/songs/templates/songs/compare.html
{% extends "base/logged_base.html" %}
{% load i18n %}

{% block page_title %}{% trans "Compare songs" %} - {% endblock page_title %}

{% block content %}
	{% if changes %}
		<h3>{% trans "Changes detected" %}</h3>
		<ul>
			{% for change in changes %}
				<li>{{ change }}</li>
			{% endfor %}

		</ul>
	{% endif %}
	{% if songs.appeared %}
		<h3>{% trans "New songs" %}</h3>
		<ul>
			{% for song in songs.appeared %}
				<li>{{ song }}</li>
			{% endfor %}
		</ul>

	{% endif %}

	{% if songs.disappeared %}
		<h3>{% trans "Removed songs" %}</h3>
		<ul>
			{% for song in songs.disappeared %}
				<li>{{ song }}</li>
			{% endfor %}
		</ul>
	{% endif %}

	{% if songs.updated %}
		<h3>{% trans "Updated songs" %}</h3>
		<dl>
			{% for song1, song2 in songs.updated.items %}
				<dt>{{ song1 }}</dt>
				<dd>{{ song2 }}</dd>
			{% endfor %}
		</dl>
	{% endif %}

	{% if not songs.appeared and not songs.disappeared and not songs.updated %}
		<h3>{% trans "Nothing to update." %}</h3>
	{% endif %}

	<form method="POST">
		{% csrf_token %}
		{{ form.as_p }}
		<button class="btn btn-primary">{% trans "OK" %}</button>
	</form>

	</ul>
{% endblock content %}

poireau/songs/templates/songs/detail.html
{% extends "base/logged_base.html" %}
{% load i18n bootstrap3 staticfiles %}

{% block page_title %}{{ object.name }} - {% endblock page_title %}

{% block content %}
	<a class='btn btn-primary pull-right' href="{% url 'songs:song_random' %}"><i class="fa fa-random"></i> {% trans "Random song" %}</a>
	<h2>{{ object.name }}</h2>
	<div class="row">
		<ul class="list-group col-md-4">
			{% for part in song.parts.all %}
				<li class="list-group-item">
					{% blocktrans with name=part.name note=part.first_note %}
						<strong>{{ name }}</strong> starts with <strong>{{ note }}</strong>
					{% endblocktrans %}
				</li>
			{% empty %}
				<li class="list-group-item">
					{% trans "No parts found in the file (or the file can't be found ?)" %}
				</li>
			{% endfor %}
		</ul>
	</div>
{% endblock content %}

poireau/songs/templates/songs/list.html
{% extends "base/logged_base.html" %}
{% load i18n bootstrap3 staticfiles %}

{% block page_title %}{% trans "Songs" %} - {% endblock page_title %}

{% block content %}
	<div class="btn-group pull-right" role="group">
		 <a class='btn btn-success' href="{% url 'songs:songs_compare' %}"><i class="fa fa-server"></i> {% trans "Update songs" %}</a>
		 <a class='btn btn-primary' href="{% url 'songs:songs_dropbox_sync' %}"><i class="fa fa-dropbox"></i> {% trans "Sync from Dropbox" %}</a>
			<a class='btn btn-default' href="{% url 'songs:song_random' %}"><i class="fa fa-random"></i> {% trans "Random song" %}</a>
	</div>
	{% regroup object_list by category as folder_list %}
	{% for folder in folder_list %}
		<h3>{{folder.grouper}} :</h3>
		<div class="row">
		{% for song in folder.list %}
			{% if forloop.counter0|divisibleby:"3" and forloop.counter0 > 0 %}
				</div><div class="row">
			{% endif %}
			<div class="col-md-4"><div class="panel panel-success">
				<div class="panel-heading"><h3 class="panel-title">
					<a href="{{ song.get_absolute_url }}"><i class="fa fa-music"></i> {{ song.name }}</a>
				</h3></div>
				<ul class="panel-body list-group">
					<li class="list-group-item">
					{% with song.parts.all|length as num_parts %}
						{% if num_parts == 0 %}
							{% trans "No parts detected in this song." %}
						{% else %}
							{% blocktrans count num_parts_l=num_parts %}
								This song has a <strong>single</strong> part
							{% plural %}
								This song has <strong>{{num_parts_l}}</strong> parts
							{% endblocktrans %}:
							{% for part in song.parts.all %}
								{{ part.name }}{% if not forloop.last %}, {% endif %}
							{% endfor %}
						{% endif %}
					{% endwith %}
					</li>
					<li class="list-group-item">
						<ul>
						<li>{% blocktrans with folder=song.folder %}In <strong>{{ folder }}</strong>{% endblocktrans %}</li>
						{% if song.date_created %}
							<li>{% blocktrans with time_since=song.date_created|timesince %}added <strong>{{ time_since }}</strong> ago{% endblocktrans %}&nbsp;</li>
						{% endif %}
						{% if song.date_modified %}
							<li>{% blocktrans with time_since=song.date_modified|timesince %}last modified <strong>{{ time_since }}</strong> ago{% endblocktrans %}</li>
						{% endif %}
						</ul>
					</li>
				</ul>
			</div></div>
		{% endfor %}
		</div>
	{% endfor %}
{% endblock content %}